name: CD

on:
  # Trigger CD when a release is published
  release:
    types: [published]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.400
    - name: Install dependencies
      run: |
        cd ./src
        dotnet restore
    - name: Build
      run: |
        cd ./src
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
       cd ./src
       dotnet test --no-restore --verbosity normal
    - name: Publish Nuget
      run: |
        cd ./src/nk.logger.csv/bin/Release/
        dotnet nuget push "*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}
