name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.402
    - name: Install dependencies
      run: |
        cd ./src
        dotnet restore
    - name: Build
      run: |
        cd ./src
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
       cd ./src
       dotnet test --no-restore --verbosity normal
