name: Label Management
on:
  # runs when a label is created/edited/deleted or when labels.yml might have been changed
    push:
      branches: 
        - master
      paths: 
        - '.github/labels.yml'
    label:
      types:
        - created
        - edited
        - deleted
        
jobs:
  labels:
    name: Label Management
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: GitHub Labeler
        uses: crazy-max/ghaction-github-labeler@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
